spring:
  config:
    import: optional:dotenv:.env

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

  mail:
    host: smtp.gmail.com
    port: ${SMTP_PORT}
    username: ${SMTP_MAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 2706

jwt:
  secret: ${JWT_SECRET}
  expiration: 604800

